package com.yeodam.yeodambe.common.response;

public enum SuccessMessage {
    ATTACHMENT_DOWNLOAD_URL_ISSUED,
    ATTACHMENT_FOUND,
    ATTACHMENT_LIST_FOUND,
    BULK_ATTACHMENT_DOWNLOAD_URL_ISSUED,
    CSRF_TOKEN_ISSUED,
    FAVORITE_REGISTERED,
    LOGIN_SUCCESS,
    ONBOARDING_REQUIRED,
    ONBOARDING_SUCCESS,
    PLACE_CANDIDATES_FOUND,
    PLACE_FOLDER_LIST_FOUND,
    TOKEN_REFRESH_SUCCESS,
    TRIP_CREATED,
    TRIP_FOUND,
    TRIP_LIST_FOUND,
    TRIP_MAP_FOUND,
    TRIP_PROCESSING_STATUS_FOUND,
    USER_FOUND
}
